[build]
  base = "packages/demo/frontend"   # Netlify will cd here before building
  publish = "dist"                  # relative to the base dir
  command = "npm ci && npm run build"

[[redirects]]
  from = "/*"
  to = "https://actions.money/:splat"
  status = 301
  force = true
  conditions = { Host = ["verbs.money", "www.verbs.money", "deploy-preview-164--verbs-ui.netlify.app"] }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
