version: 2.1

orbs:
  nx: nrwl/nx@1.7.0
  utils: ethereum-optimism/circleci-utils@1.0.27

commands:
  prepare-snapshot:
    description: 'Prepare the snapshot name'
    steps:
      - run:
          name: Setup snapshot name
          command: |
            SNAPSHOT_NAME=${CIRCLE_BRANCH}
            echo "Will create snapshot using name $SNAPSHOT_NAME"
            echo "export SNAPSHOT_NAME=${SNAPSHOT_NAME}" >> "$BASH_ENV"
      - run:
          name: Prepare changeset version environment
          command: |
            echo "export GITHUB_TOKEN=${GITHUB_TOKEN_GOVERNANCE}" >> "$BASH_ENV"
      - run:
          name: Create snapshot versions
          command: pnpm release:version:snapshot

  setup:
    description: 'Setup Node.js environment with pnpm'
    steps:
      - run:
          name: Set GITHUB_TOKEN for mise
          command: echo 'export GITHUB_TOKEN=${MISE_GITHUB_TOKEN}' >> $BASH_ENV
      - utils/checkout-with-mise # Install dependencies
      - run:
          name: Install dependencies
          environment:
            NPM_TOKEN: nada
          command: |
            pnpm i --frozen-lockfile

jobs:
  publish-to-npm:
    docker:
      - image: cimg/node:22.14
    resource_class: large
    parameters:
      prepare-snapshot:
        type: boolean
        default: false
    steps:
      - setup
      - run:
          name: Install npm with OIDC trusted publishing support
          command: npm install -g npm@11.12.1
      - run:
          name: Build projects
          environment:
            NPM_TOKEN: nada
          command: NODE_OPTIONS='--max-old-space-size=4096' pnpm nx run-many --target=build --parallel=1
      - run:
          name: Obtain OIDC token for npm trusted publishing
          command: |
            echo "export NPM_ID_TOKEN=$(circleci run oidc get --claims '{\"aud\": \"npm:registry.npmjs.org\"}')" >> "$BASH_ENV"

      - when:
          condition:
            equal: [<< parameters.prepare-snapshot >>, true]
          steps:
            - prepare-snapshot

      - utils/changesets:
          createGithubReleases: false
          publish: 'pnpm release:publish'
          version: 'pnpm release:version'

  check:
    docker:
      - image: cimg/node:20.11
    resource_class: large
    steps:
      - setup
      - run:
          name: Run Build
          command: NODE_OPTIONS='--max-old-space-size=4096' pnpm nx run-many --target=build --parallel=1
      - run:
          name: Run TypeChecker
          command: pnpm typecheck
      - run:
          name: Run Linters
          command: pnpm lint
      - run:
          name: Run SDK Tests
          command: cd packages/sdk && pnpm test
      - run:
          name: Run Frontend Tests
          command: cd packages/demo/frontend && pnpm test
      - run:
          name: Run Backend Tests
          command: cd packages/demo/backend && pnpm test
      - run:
          name: Run Contracts Build and Tests
          command: cd packages/demo/contracts && pnpm build && pnpm test

workflows:
  release:
    jobs:
      - publish-to-npm:
          name: Publish new versions
          context:
            - circleci-repo-actions # for GITHUB_TOKEN_GOVERNANCE
            - circleci-repo-readonly-authenticated-github-token #needed for MISE
          filters:
            branches:
              only: main

      - publish-to-npm:
          name: Publish snapshot versions
          prepare-snapshot: true
          context:
            - circleci-repo-actions # for GITHUB_TOKEN_GOVERNANCE
            - circleci-repo-readonly-authenticated-github-token #needed for MISE
          filters:
            branches:
              only: main

  check-workflow:
    jobs:
      - check:
          context:
            - circleci-repo-readonly-authenticated-github-token

