import {
  base,
  baseSepolia,
  bob,
  fraxtal,
  ink,
  lisk,
  mainnet,
  metalL2,
  mode,
  optimism,
  optimismSepolia,
  sepolia,
  soneium,
  swellchain,
  unichain,
  unichainSepolia,
  worldchain,
} from 'viem/chains'

export const SUPPORTED_CHAIN_IDS = [
  mainnet.id,
  sepolia.id,
  optimism.id,
  optimismSepolia.id,
  base.id,
  baseSepolia.id,
  unichain.id,
  unichainSepolia.id,
  worldchain.id,
  soneium.id,
  ink.id,
  mode.id,
  fraxtal.id,
  lisk.id,
  bob.id,
  swellchain.id,
  metalL2.id,
] as const

export type SupportedChainId = (typeof SUPPORTED_CHAIN_IDS)[number]
