# .github/workflows/sleep-on-merge.yml
name: Sleep on Merge

on:
  pull_request_target:
    types: [closed]

jobs:
  sleep-job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sleep for 30 seconds
        run: |
          sleep 30
